insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Ercan','Эркан','Еркан','34.9091','33.6359','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Gecitkale','Геситкале','Гесіткале','34.9091','33.6359','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Larnaca','Ларнака','Ларнака','34.9091','33.6359','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Nicosia','Никозия','Нікосія','35.1716','33.3613','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Paphos','Пафос','Пафос','34.7836','32.4256','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('AYIA NAPA','AYIA NAPA','AYIA NAPA','34.9897','33.9993','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('LIMASSOL','LIMASSOL','LIMASSOL','34.6818','33.0432','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Protaras','Protaras','Protaras','35.0187','34.0469','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Polis','Polis','Polis','35.0342','32.4264','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Kyrenia','Kyrenia','Kyrenia','35.0342','32.5231','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Kakopetria','Kakopetria','Kakopetria','34.994','32.9137','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Skarinou','Skarinou','Skarinou','34.8266','33.3593','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Agros','Agros','Agros','34.8266','32.5231','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Nea Dhimmata','Nea Dhimmata','Nea Dhimmata','35.1331','32.5231','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Vouni','Vouni','Vouni','34.825','32.8333','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Voroklini','Вороклини','Voroklini','34.9833','33.6583','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Vavla','Vavla','Vavla','34.8417','33.2667','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Vasilia','Василия','Vasilia','35.3458','33.125','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Troulli','Troulli','Troulli','35.0333','33.6167','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Trimiklini','Trimiklini','Trimiklini','34.8458','32.9125','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Tochni','Тохни','Tochni','34.7819','33.3249','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Timi','Timi','Timi','34.7333','32.5167','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Theletra','Theletra','Theletra','34.9167','32.4542','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Tersephanou','Терсефану','Tersephanou','34.8542','33.5458','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Tala','Tala','Tala','34.8491','32.4372','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Sykopetra','Sykopetra','Sykopetra','34.8792','33.1125','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Stroumbi','Stroumbi','Stroumbi','34.8833','32.4833','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Steni','Steni','Steni','34.9958','32.4708','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Spilia','Spilia','Spilia','34.9667','32.9542','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Pyla','Pyla','Pyla','35.0292','33.6917','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Psematismenos','Psematismenos','Psematismenos','34.7667','33.3458','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Prodhromos','Prodhromos','Prodhromos','34.9497','32.8306','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Potamitissa','Потамитисса','Potamitissa','34.908','32.9895','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Pomos','Pomos','Pomos','35.1564','32.5478','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Polis Chrysochous','Полис','Polis Chrysochous','35.0367','32.4264','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Polemi','Polemi','Polemi','34.8875','32.5','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Pissouri','Писсури','Pissouri','34.6585','32.7191','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Phasoula','Фасула','Phasoula','34.7667','33.0292','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Peyia','Пейя','Пейя','34.8833','32.3833','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Perivolia','Периволия','Perivolia','34.8292','33.5833','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Peristerona','Peristerona','Peristerona','34.9917','32.4917','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Pendalia','Pendalia','Pendalia','34.8583','32.6167','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Pendakomo','Пендакомо','Pendakomo','34.7417','33.2417','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Pedoulas','Педулас','Pedoulas','34.9667','32.8292','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Paralimni','Паралимни','Paralimni','35.0415','33.9955','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Platres','Пано-Платрес','Platres','34.8873','32.867','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Pano Lefkara','Пано-Лефкара','Pano Lefkara','34.8667','33.3042','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Pano Arodhes','Pano Arodhes','Пано Ародес','34.9375','32.4083','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Pano Akourdhalia','Pano Akourdhalia','Pano Akourdhalia','34.9417','32.4458','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Palekhori','Palekhori','Palekhori','34.925','33.0917','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Pakhyammos','Pakhyammos','Pakhyammos','35.1681','32.5872','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Pakhna','Pakhna','Pakhna','34.7792','32.7958','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Omodhos','Omodhos','Omodhos','34.85','32.8083','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Nikoklia','Никоклия','Нікоклія','34.7292','32.575','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Moniatis','Moniatis','Moniatis','34.8708','32.8958','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Moni','Moni','Moni','34.7333','33.2','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Miliou','Милиу','Міліу','34.9333','32.469','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Mesa Khorio','Mesa Khorio','Mesa Khorio','34.8083','32.4625','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Mazotos','Мазотос','Mazotos','34.7886','33.4886','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Maroni','Maroni','Maroni','34.7383','33.3803','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Mandria','Мадрия','Мадрія','34.7104','32.5302','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Lythrodhondas','Литродонда','Lythrodhondas','34.95','33.2958','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Lyso','Lyso','Lyso','34.9958','32.5125','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Lemithou','Лемиту','Lemithou','34.95','32.8167','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Lasa','Lasa','Lasa','34.925','32.5292','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Lapithos','Лапитос','Lapithos','35.3375','33.1792','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Lania','Lania','Lania','34.825','32.9208','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Kouklia','Куклия','Куклія','34.6844','32.6046','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Kinousa','Kinousa','Kinousa','35.0319','32.5114','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Khoulou','Khoulou','Хулу','34.8708','32.5542','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Khirokitia','Khirokitia','Khirokitia','34.7958','33.3375','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Kato Pyrgos','Kato Pyrgos','Kato Pyrgos','35.1803','32.6825','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Kato Dhrys','Като-Дрис','Kato Dhrys','34.85','33.3042','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Kato Akourdhalia','Kato Akourdhalia','Kato Akourdhalia','34.9542','32.45','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Kathikas','Катикас','Катікас','34.9167','32.425','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Kambia','Kambia','Kambia','35.0083','33.2583','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Kalopanayiotis','Kalopanayiotis','Kalopanayiotis','34.9917','32.825','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Kallepia','Kallepia','Калепія','34.8458','32.5','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Kalavasos','Калавасос','Kalavasos','34.7743','33.2957','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Inia','Inia','Inia','34.9583','32.3917','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Gourri','Гурри','Gourri','34.9583','33.1583','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Goudhi','Goudhi','Goudhi','34.9917','32.4417','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Ghaziveran','Газиверан','Ghaziveran','35.1728','32.9169','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Galata','Galata','Galata','34.9958','32.9','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Erimi','Эрими','Erimi','34.687','32.9221','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Episkopi','Episkopi','Епископи','34.7958','32.525','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Dhrymou','Dhrymou','Dhrymou','34.925','32.5167','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Droushia','Друсия','Droushia','34.9689','32.4016','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Dherinia','Dherinia','Dherinia','35.0667','33.9583','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Ayios Tykhonas','Агиос-Тихонас','Ayios Tykhonas','34.725','33.1417','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Ayios Theodhoros','Айос-Теодорос','Ayios Theodhoros','34.8014','33.3875','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Ayios Photios','Ayios Photios','Ayios Photios','34.875','32.6125','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Ayios Mamas','Ayios Mamas','Ayios Mamas','34.85','32.95','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Ayia Marina','Ayia Marina','Ayia Marina','35.1125','32.5375','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Athienou','Athienou','Athienou','35.0667','33.5417','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Arsos','Арсос','Arsos','34.8417','32.7708','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Armou','Armou','Armou','34.8','32.4792','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Argaka','Argaka','Argaka','35.0644','32.5','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Apsiou','Апсиу','Apsiou','34.7969','33.0172','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Anoyira','Anoyira','Anoyira','34.7458','32.7333','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Anarita','Anarita','Anarita','34.7417','32.5333','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Anaphotia','Anaphotia','Anaphotia','34.825','33.4625','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Vasa','Васа','Vasa','34.8333','32.7917','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Sotira','Сотира','Сотира','34.9974','33.9282','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Ayia Marina Chrysochous','Айя-Марина Хрисохус','Айя-Марина Хрисохус','35.1243','32.514','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Kiti','Кити','Кити','34.853','33.5774','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Choirokoitia','Хирокития','Хирокития','34.8029','33.3451','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Lefkara','Лекара','Лекара','34.8716','33.3133','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Kato Drys','Като-Дрис','Като-Дрис','34.8537','33.3187','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Dhekelia','Декелия','Декелия','34.9868','33.76','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Kato Akourdalia','Като-Акурдалия','Като-Акурдалия','34.9609','32.4569','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Lysos','Лисос','Лисос','34.9997','32.5158','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Agios Theodoros','Агиос-Теодорос','Агиос-Теодорос','34.7975','33.3846','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Pervolia','Пляж Pervolia','Пляж Pervolia','34.8219','33.606','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Oroklini','Ороклини','Ороклини','34.9824','33.6602','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Fasoula','Фасула','Фасула','34.7597','33.0277','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Pegeia','Пейя','Пейя','34.8772','32.3552','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Kissonerga','Киссонерга','Киссонерга','34.8295','32.394','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Geroskipou','Героскипу','Героскипу','34.7652','32.4626','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Nikokleia','Никоклея','Никоклея','34.7311','32.5761','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Old Town of Limassol','Old Town of Limassol','Old Town of Limassol','34.6778','33.0451','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Makronissos Beach','Пляж Макрониссос','Пляж Макрониссос','34.9832','33.9523','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Tersefanou','Терсефану','Терсефану','34.8538','33.5455','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Troodos','Троодос','Троодос','34.9242','32.8817','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Pedhoulas','Педулас','Педулас','34.9734','32.8285','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Souni-Zanakia','Суни-Занакия','Суни-Занакия','34.7344','32.8932','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Lythrodontas','Литродонтас','Литродонтас','34.9509','33.3019','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Sunrise Beach','Sunrise Beach','Sunrise Beach','35.0183','34.0533','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Latchi Beach','Пляж Latchi Beach','Пляж Latchi Beach','35.0411','32.4081','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Latsia','Лация','Лация','35.0986','33.38','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Tseri','Цери','Цери','35.0714','33.3257','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Avgorou','Авгору','Авгору','35.0364','33.8362','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Goudi','Гоуди','Гоуди','34.9929','32.4414','CY');
insert into `cities` (`name_en`, `name_ru`, `name_uk`, `lat`, `lng`, `country`) values('Agia Varvara','Agia Varvara','Agia Varvara','34.997','33.3719','CY');
