 
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Andorra','Андорра','Андора','376','AD');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('United Arab Emirates','ОАЭ','Обєднані Арабські Емірати','971','AE');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Afghanistan','Афганистан','Афганістан','93','AF');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Antigua and Barbuda','Антигуа и Барбуда','Антигуа і Барбуда ','1268','AG');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Anguilla','Ангилья','Ангілья','1264','AI');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Albania','Албания','Албанія','355','AL');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Armenia','Армения','Вірменія','374','AM');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Netherlands Antilles','Нидерландские Антильские острова','Нідерландські Антильські острови','599','AN');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Angola','Ангола','Ангола','244','AO');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Argentina','Аргентина','Аргентина','54','AR');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('American Samoa','Американское Самоа','Американське Самоа','684','AS');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Austria','Австрия','Австрія','43','AT');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Australia','Австралия','Австралія','61','AU');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Aruba','Аруба','Аруба','297','AW');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Azerbaijan','Азербайджан','Азербайджан','994','AZ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Bosnia-Herzegovina','Босния и Герцеговина','Боснія і Герцоговина','387','BA');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Barbados','Барбадос','Барбадос','1246','BB');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Bangladesh','Бангладеш','Бангладеш','880','BD');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Belgium','Бельгия','Бельгія','32','BE');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Burkina Faso','Буркина-Фасо','Буркіна-Фасо','226','BF');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Bulgaria','Болгария','Болгарія','359','BG');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Bahrain','Бахрейн','Бахрейн ','973','BH');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Burundi','Бурунди','Бурунді ','257','BI');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Benin','Бенин','Бенін ','229','BJ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Bermuda','Бермудские острова','Бермудські острови','1441','BM');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Brunei Darussalam','Бруней-Даруссалам','Бруней-Даруссалам','673','BN');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Bolivia','Боливия','Болівія','591','BO');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Brazil','Бразилия','Бразилія','55','BR');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Bahamas','Багамские острова','Багамські острови','1242','BS');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Bhutan','Бутан','Бутан','975','BT');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Botswana','Ботсвана','Боствана','267','BW');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Belarus','Беларусь','Білорусь ','375','BY');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Belize','Белиз','Беліз','501','BZ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Canada','Канада','Канада','1','CA');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Cocos Island','Кокосовые острова','Кокосові острови','6722','CC');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Congo (Democratic Republic of)','Конго','Конго','242','CD');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Central African Republic','Центральноафриканская Республика','Центрально-Африканська Республіка','236','CF');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Congo Brazzaville','Конго Браззавиль','Конго Браззавіль','242','CG');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Switzerland','Швейцария','Швейцарія','41','CH');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Cote dIvoire','Кот дИвуар','Кот дІвуар','225','CI');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Cook Islands','Острова Кука','Острови Кука','682','CK');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Chile','Чили','Чилі','56','CL');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Cameroon (Republic of)','Камерун','Камерун','237','CM');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('China','Китай','Китай','86','CN');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Colombia','Колумбия','Колумбія','57','CO');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Costa Rica','Коста-Рика','Коста-Ріка ','506','CR');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Cuba','Куба','Куба','53','CU');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Cape Verde (Republic of)','Кабо-Верде','Кабо-Верде','238','CV');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Christmas Island','Остров Рождества','Острів Різдва','6724','CX');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Cyprus','Кипр','Кіпр','357','CY');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Czech Republic','Чехия','Чехія','420','CZ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Germany','Германия','Німеччина','49','DE');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Djibouti','Джибути','Джибуті ','253','DJ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Denmark','Дания','Данія','45','DK');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Dominica','Доминика','Домініка','1767','DM');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Dominican Republic','Доминиканская Республика','Домініканська Республіка','1809','DO');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Algeria','Алжир','Алжир','213','DZ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Ecuador','Эквадор','Еквадор','593','EC');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Estonia','Эстония','Естонія','372','EE');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Egypt','Египет','Єгипет','20','EG');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Eritrea','Эритрея','Еритрея','291','ER');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Spain','Испания','Іспанія','34','ES');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Ethiopia','Эфиопия','Ефіопія','251','ET');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Finland','Финляндия','Фінляндія ','358','FI');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Fiji','Фиджи','Фіджі ','679','FJ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Falkland Islands','Фоклендские острова','Фолклендські острови ','500','FK');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Micronesia','Микронезия','Мікронезія ','691','FM');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Faroe Islands','Фарерские острова','Фарерські острови ','298','FO');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('France','Франция','Франція','33','FR');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Gabon','Габон','Габон','241','GA');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('United Kingdom','Великобритания','Великобританія','44','GB');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Grenada','Гренада','Гренада','1473','GD');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Georgia','Грузия','Грузія','995','GE');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('French Guiana','Французская Гвиана','Французька Гвіана ','594','GF');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Ghana','Гана','Ґана','233','GH');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Gibraltar','Гибралтар','Гібралтар ','350','GI');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Greenland','Гренландия','Ґренландія','299','GL');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Gambia','Гамбия','Гамбія ','220','GM');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Guinea','Гвинея','Ґвінея','224','GN');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Guadeloupe','Гваделупа','Гваделупа','590','GP');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Equatorial Guinea','Экваториальная Гвинея','Екваторіальна Гвінея','240','GQ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Greece','Греция','Греція','30','GR');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Guatemala','Гватемала','Гватемала','502','GT');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Guam','Гуам','Гуам','671','GU');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Guinea Bissau','Гвинея-Бисау','Ґвінея-Бісау','245','GW');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Guyana','Гайана','Гайана ','592','GY');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Hong Kong (SAR of China)','Гонконг','Гонконг ','852','HK');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Honduras','Гондурас','Гондурас','504','HN');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Croatia','Хорватия','Хорватія','385','HR');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Haiti','Гаити','Гаїті','509','HT');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Hungary','Венгрия','Угорщина','36','HU');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Indonesia','Индонезия','Індонезія','62','ID');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Ireland (Republic of)','Ирландия','Ірландія','353','IE');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Israel','Израиль','Ізраїль','972','IL');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('India','Индия','Індія','91','IN');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Iraq','Ирак','Ірак','964','IQ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Iran','Иран','Іран','98','IR');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Iceland','Исландия','Ісландія','354','IS');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Italy','Италия','Італія','39','IT');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Jamaica','Ямайка ','Ямайка','1876','JM');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Jordan','Иордания','Йорданія','962','JO');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Japan','Япония','Японія','81','JP');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Kenya','Кения','Кенія','254','KE');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Kyrgyzstan','Кыргызстан','Киргизстан ','996','KG');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Cambodia Riel','Камбоджа','Камбоджа','855','KH');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Kiribati','Кирибати','Кірибаті','686','KI');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Comoros','Коморские острова','Коморські острови','269','KM');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('St Kitts','Сент-Киттс','Сент-Кітс ','869','KN');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Korea (Democratic Peoples Republic Of)','Корея','Корейська Народна Демократична Республіка','850','KP');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Korea (Republic of)','Корея','Республіка Корея ','82','KR');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Kuwait','Кувейт','Кувейт','965','KW');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Cayman Islands','Каймановы острова','Кайманові острови','1345','KY');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Kazakhstan','Казахстан','Казахстан','7','KZ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Lao (Peoples Democratic Republic)','Лаос','Лаос','856','LA');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Lebanon','Ливан','Ліван','961','LB');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('St. Lucia','Сент-Люсия','Сент-Люсія ','1758','LC');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Liechtenstein','Лихтенштейн','Ліхтенштейн','423','LI');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Sri Lanka','Шри-Ланка','Шрі-Ланка','94','LK');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Liberia','Либерия','Ліберія','231','LR');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Lesotho','Лесото','Лесото','266','LS');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Lithuania','Литва','Литва','370','LT');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Luxembourg','Люксембург','Люксембург','352','LU');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Latvia','Латвия','Латвія','371','LV');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Libyan Arab Jamahiriya','Ливия','Лівія','218','LY');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Morocco','Марокко','Марокко','212','MA');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Monaco','Монако','Монако','377','MC');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Moldova','Молдавия','Молдова','373','MD');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Montenegro','Черногория','Чорногорія','382','ME');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Madagascar Island','Мадагаскар','Мадагаскар','261','MG');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Marshall Islands','Маршалловы острова','Маршаллові Острови','692','MH');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Macedonia - FYROM','Македония','Македонія','389','MK');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Mali','Мали','Малі','223','ML');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Myanmar','Мьянма','Мянма ','95','MM');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Mongolia','Монголия','Монголія','976','MN');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Macao - SAR of China','Макао','Макао ','853','MO');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Northern Mariana Islands','Северные Марианские Острова','Північні Маріанські Острови','1670','MP');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Martinique','Мартиника','Мартініка ','596','MQ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Mauritania','Мавритания','Мавританія ','222','MR');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Montserrat','Монсеррат','Монтсеррат ','1664','MS');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Malta','Мальта','Мальта','356','MT');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Mauritius Island','Маврикий','Маврикій','230','MU');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Maldives Islands','Мальдивы','Мальдіви ','960','MV');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Malawi','Малави','Малаві','265','MW');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Mexico','Мексика','Мексика','52','MX');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Malaysia','Малайзия','Малайзія','60','MY');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Mozambique','Мозамбик','Мозамбік','258','MZ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Namibia','Намибия','Намібія','264','NA');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('New Caledonia','Новая Каледония','Нова Каледонія','687','NC');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Niger','Нигер','Нігер ','227','NE');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Norfolk Island','Норфолк Айленд','Норфолк Айленд ',NULL,'NF');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Nigeria','Нигерия','Нігерія','234','NG');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Nicaragua','Никарагуа','Нікарагуа','505','NI');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Netherlands','Нидерланды','Нідерланди','31','NL');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Norway','Норвегия','Норвегія','47','NO');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Nepal','Непал','Непал','977','NP');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Nauru','Науру','Науру','674','NR');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Niue','Ниуэ','Ніуе ','683','NU');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('New Zealand','Новая Зеландия','Нова Зеландія','64','NZ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Oman','Оман','Оман','968','OM');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Panama','Панама','Панама','507','PA');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Peru','Перу','Перу','51','PE');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('French Polynesia','Французская Полинезия','Французька Полінезія ','689','PF');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Papua New Guinea','Папуа - Новая Гвинея','Папуа Нова Гвінея','675','PG');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Philippines','Филиппины','Філіпіни','63','PH');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Pakistan','Пакистан','Пакистан','92','PK');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Poland','Польша','Польща','48','PL');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('St. Pierre and Miquelon','Сен-Пьер и Микелон','Сен Пєр та Мікелон','508','PM');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Puerto Rico','Пуэрто Рико','Пуерто-Ріко ','1787','PR');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Palestinian Occ. Territories','Палестина','Палестина','972','PS');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Portugal','Португалия','Португалія','351','PT');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Palau Islands','Палау','Палау','680','PW');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Paraguay','Парагвай','Парагвай','595','PY');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Qatar','Катар','Катар','974','QA');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Reunion Island','Реюньон','Реюньйон ','262','RE');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Romania','Румыния','Румунія','40','RO');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Serbia','Сербия','Сербія','381','RS');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Russia','Россия','Росія','7','RU');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Rwanda','Руанда','Руанда','250','RW');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Saudi Arabia','Саудовская Аравия','Саудівська Аравія','966','SA');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Solomon Islands','Соломоновы острова','Соломонові Острови ','677','SB');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Seychelles Islands','Сейшельские острова','Сейшели','248','SC');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Sudan','Судан','Судан','249','SD');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Sweden','Швеция','Швеція','46','SE');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Singapore','Сингапур','Сінгапур','65','SG');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('St. Helena Island','Остров святой Елены','Острів Святої Єлени ','290','SH');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Slovenia','Словения','Словенія','386','SI');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Slovakia','Словакия','Словаччина','421','SK');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Sierra Leone','Сьерра-Леоне','Сьєрра-Леоне ','232','SL');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('San Marino','Сан-Марино','Сан-Марино ','378','SM');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Senegal','Сенегал','Сенегал','221','SN');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Somalia','Сомали','Сомалі','252','SO');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Suriname','Суринам','Сурінам ','597','SR');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Sao Tome and Principe Islands','Сан-Томе и Принсипи','Сан-Томе і Принсіпі','239','ST');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('El Salvador','Сальвадор','Сальвадор','503','SV');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Syrian Arab Republic','Сирия','Сирія','963','SY');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Swaziland','Свазиленд','Свазіленд','268','SZ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Turks and Caicos Islands','Теркс и Кайкос','Теркс і Кайкос',NULL,'TC');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Chad','Чад','Чад','235','TD');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Togo','Того','Того','228','TG');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Thailand','Таиланд','Таїланд','66','TH');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Tajikistan','Таджикистан','Таджикистан','992','TJ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Timor Leste','Тимор-Лешти','Тимор-Лешті','670','TL');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Turkmenistan','Туркменистан','Туркменістан','993','TM');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Tunisia','Тунис','Туніс','216','TN');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Tonga','Тонга','Тонга','676','TO');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Turkey','Турция','Туреччина','90','TR');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Trinidad and Tobago','Тринидад и Тобаго','Тринідад і Тобаго','1868','TT');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Tuvalu','Тувалу','Тувалу','688','TV');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Taiwan','Тайвань','Тайвань','886','TW');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Tanzania (United Republic)','Танзания','Танзанія','255','TZ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Ukraine','Украина','Україна','38','UA');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Uganda','Уганда','Уганда','256','UG');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('U.S. Minor Outlying Islands','Внешние малые острова (CШA)','Зовнішні малі острови (CШA)','1','UM');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('USA','США','Сполучені Штати Америки','1','US');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Uruguay','Уругвай','Уругвай','598','UY');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Uzbekistan','Узбекистан','Узбекистан','998','UZ');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('St Vincent and the Grenadines','Сент-Винсент и Гренадины','Сент-Вінсент і Ґренадини','1784','VC');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Venezuela','Венесуэла','Венесуела','58','VE');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Virgin Islands (British)','Британские Виргинские острова','Британські Віргінські острови','1284','VG');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Virgin Islands US','Американские Виргинские острова','Американські Віргінські острови','1284','VI');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Viet Nam','Вьетнам','Вєтнам','84','VN');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Vanuatu','Вануату','Вануату','678','VU');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Wallis and Futuna Islands','Острова Уоллис и Футун','Острови Волліс і Футуна ','681','WF');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Samoa (Independent State of)','Самоа','Самоа','685','WS');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Yemen (Arab Republic)','Йемен','Ємен','967','YE');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Mayotte','Майотта','Майотта','269','YT');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('South Africa','ЮАР','Південно-африканська республіка','27','ZA');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Zambia','Замбия','Замбія','260','ZM');
insert into `countries` ( `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('Zimbabwe','Зимбабве','Зімбабве','263','ZW');
