 
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('AD','Andorra','Андорра','Андора','376','AD');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('AE','United Arab Emirates','ОАЭ','Обєднані Арабські Емірати','971','AE');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('AF','Afghanistan','Афганистан','Афганістан','93','AF');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('AG','Antigua and Barbuda','Антигуа и Барбуда','Антигуа і Барбуда ','1268','AG');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('AI','Anguilla','Ангилья','Ангілья','1264','AI');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('AL','Albania','Албания','Албанія','355','AL');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('AM','Armenia','Армения','Вірменія','374','AM');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('AN','Netherlands Antilles','Нидерландские Антильские острова','Нідерландські Антильські острови','599','AN');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('AO','Angola','Ангола','Ангола','244','AO');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('AR','Argentina','Аргентина','Аргентина','54','AR');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('AS','American Samoa','Американское Самоа','Американське Самоа','684','AS');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('AT','Austria','Австрия','Австрія','43','AT');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('AU','Australia','Австралия','Австралія','61','AU');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('AW','Aruba','Аруба','Аруба','297','AW');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('AZ','Azerbaijan','Азербайджан','Азербайджан','994','AZ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BA','Bosnia-Herzegovina','Босния и Герцеговина','Боснія і Герцоговина','387','BA');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BB','Barbados','Барбадос','Барбадос','1246','BB');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BD','Bangladesh','Бангладеш','Бангладеш','880','BD');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BE','Belgium','Бельгия','Бельгія','32','BE');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BF','Burkina Faso','Буркина-Фасо','Буркіна-Фасо','226','BF');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BG','Bulgaria','Болгария','Болгарія','359','BG');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BH','Bahrain','Бахрейн','Бахрейн ','973','BH');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BI','Burundi','Бурунди','Бурунді ','257','BI');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BJ','Benin','Бенин','Бенін ','229','BJ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BM','Bermuda','Бермудские острова','Бермудські острови','1441','BM');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BN','Brunei Darussalam','Бруней-Даруссалам','Бруней-Даруссалам','673','BN');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BO','Bolivia','Боливия','Болівія','591','BO');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BR','Brazil','Бразилия','Бразилія','55','BR');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BS','Bahamas','Багамские острова','Багамські острови','1242','BS');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BT','Bhutan','Бутан','Бутан','975','BT');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BW','Botswana','Ботсвана','Боствана','267','BW');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BY','Belarus','Беларусь','Білорусь ','375','BY');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('BZ','Belize','Белиз','Беліз','501','BZ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CA','Canada','Канада','Канада','1','CA');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CC','Cocos Island','Кокосовые острова','Кокосові острови','6722','CC');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CD','Congo (Democratic Republic of)','Конго','Конго','242','CD');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CF','Central African Republic','Центральноафриканская Республика','Центрально-Африканська Республіка','236','CF');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CG','Congo Brazzaville','Конго Браззавиль','Конго Браззавіль','242','CG');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CH','Switzerland','Швейцария','Швейцарія','41','CH');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CI','Cote dIvoire','Кот дИвуар','Кот дІвуар','225','CI');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CK','Cook Islands','Острова Кука','Острови Кука','682','CK');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CL','Chile','Чили','Чилі','56','CL');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CM','Cameroon (Republic of)','Камерун','Камерун','237','CM');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CN','China','Китай','Китай','86','CN');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CO','Colombia','Колумбия','Колумбія','57','CO');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CR','Costa Rica','Коста-Рика','Коста-Ріка ','506','CR');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CU','Cuba','Куба','Куба','53','CU');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CV','Cape Verde (Republic of)','Кабо-Верде','Кабо-Верде','238','CV');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CX','Christmas Island','Остров Рождества','Острів Різдва','6724','CX');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CY','Cyprus','Кипр','Кіпр','357','CY');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('CZ','Czech Republic','Чехия','Чехія','420','CZ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('DE','Germany','Германия','Німеччина','49','DE');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('DJ','Djibouti','Джибути','Джибуті ','253','DJ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('DK','Denmark','Дания','Данія','45','DK');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('DM','Dominica','Доминика','Домініка','1767','DM');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('DO','Dominican Republic','Доминиканская Республика','Домініканська Республіка','1809','DO');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('DZ','Algeria','Алжир','Алжир','213','DZ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('EC','Ecuador','Эквадор','Еквадор','593','EC');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('EE','Estonia','Эстония','Естонія','372','EE');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('EG','Egypt','Египет','Єгипет','20','EG');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('ER','Eritrea','Эритрея','Еритрея','291','ER');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('ES','Spain','Испания','Іспанія','34','ES');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('ET','Ethiopia','Эфиопия','Ефіопія','251','ET');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('FI','Finland','Финляндия','Фінляндія ','358','FI');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('FJ','Fiji','Фиджи','Фіджі ','679','FJ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('FK','Falkland Islands','Фоклендские острова','Фолклендські острови ','500','FK');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('FM','Micronesia','Микронезия','Мікронезія ','691','FM');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('FO','Faroe Islands','Фарерские острова','Фарерські острови ','298','FO');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('FR','France','Франция','Франція','33','FR');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GA','Gabon','Габон','Габон','241','GA');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GB','United Kingdom','Великобритания','Великобританія','44','GB');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GD','Grenada','Гренада','Гренада','1473','GD');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GE','Georgia','Грузия','Грузія','995','GE');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GF','French Guiana','Французская Гвиана','Французька Гвіана ','594','GF');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GH','Ghana','Гана','Ґана','233','GH');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GI','Gibraltar','Гибралтар','Гібралтар ','350','GI');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GL','Greenland','Гренландия','Ґренландія','299','GL');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GM','Gambia','Гамбия','Гамбія ','220','GM');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GN','Guinea','Гвинея','Ґвінея','224','GN');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GP','Guadeloupe','Гваделупа','Гваделупа','590','GP');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GQ','Equatorial Guinea','Экваториальная Гвинея','Екваторіальна Гвінея','240','GQ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GR','Greece','Греция','Греція','30','GR');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GT','Guatemala','Гватемала','Гватемала','502','GT');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GU','Guam','Гуам','Гуам','671','GU');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GW','Guinea Bissau','Гвинея-Бисау','Ґвінея-Бісау','245','GW');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('GY','Guyana','Гайана','Гайана ','592','GY');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('HK','Hong Kong (SAR of China)','Гонконг','Гонконг ','852','HK');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('HN','Honduras','Гондурас','Гондурас','504','HN');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('HR','Croatia','Хорватия','Хорватія','385','HR');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('HT','Haiti','Гаити','Гаїті','509','HT');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('HU','Hungary','Венгрия','Угорщина','36','HU');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('ID','Indonesia','Индонезия','Індонезія','62','ID');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('IE','Ireland (Republic of)','Ирландия','Ірландія','353','IE');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('IL','Israel','Израиль','Ізраїль','972','IL');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('IN','India','Индия','Індія','91','IN');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('IQ','Iraq','Ирак','Ірак','964','IQ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('IR','Iran','Иран','Іран','98','IR');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('IS','Iceland','Исландия','Ісландія','354','IS');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('IT','Italy','Италия','Італія','39','IT');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('JM','Jamaica','Ямайка ','Ямайка','1876','JM');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('JO','Jordan','Иордания','Йорданія','962','JO');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('JP','Japan','Япония','Японія','81','JP');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('KE','Kenya','Кения','Кенія','254','KE');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('KG','Kyrgyzstan','Кыргызстан','Киргизстан ','996','KG');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('KH','Cambodia Riel','Камбоджа','Камбоджа','855','KH');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('KI','Kiribati','Кирибати','Кірибаті','686','KI');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('KM','Comoros','Коморские острова','Коморські острови','269','KM');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('KN','St Kitts','Сент-Киттс','Сент-Кітс ','869','KN');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('KP','Korea (Democratic Peoples Republic Of)','Корея','Корейська Народна Демократична Республіка','850','KP');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('KR','Korea (Republic of)','Корея','Республіка Корея ','82','KR');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('KW','Kuwait','Кувейт','Кувейт','965','KW');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('KY','Cayman Islands','Каймановы острова','Кайманові острови','1345','KY');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('KZ','Kazakhstan','Казахстан','Казахстан','7','KZ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('LA','Lao (Peoples Democratic Republic)','Лаос','Лаос','856','LA');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('LB','Lebanon','Ливан','Ліван','961','LB');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('LC','St. Lucia','Сент-Люсия','Сент-Люсія ','1758','LC');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('LI','Liechtenstein','Лихтенштейн','Ліхтенштейн','423','LI');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('LK','Sri Lanka','Шри-Ланка','Шрі-Ланка','94','LK');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('LR','Liberia','Либерия','Ліберія','231','LR');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('LS','Lesotho','Лесото','Лесото','266','LS');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('LT','Lithuania','Литва','Литва','370','LT');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('LU','Luxembourg','Люксембург','Люксембург','352','LU');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('LV','Latvia','Латвия','Латвія','371','LV');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('LY','Libyan Arab Jamahiriya','Ливия','Лівія','218','LY');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MA','Morocco','Марокко','Марокко','212','MA');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MC','Monaco','Монако','Монако','377','MC');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MD','Moldova','Молдавия','Молдова','373','MD');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('ME','Montenegro','Черногория','Чорногорія','382','ME');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MG','Madagascar Island','Мадагаскар','Мадагаскар','261','MG');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MH','Marshall Islands','Маршалловы острова','Маршаллові Острови','692','MH');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MK','Macedonia - FYROM','Македония','Македонія','389','MK');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('ML','Mali','Мали','Малі','223','ML');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MM','Myanmar','Мьянма','Мянма ','95','MM');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MN','Mongolia','Монголия','Монголія','976','MN');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MO','Macao - SAR of China','Макао','Макао ','853','MO');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MP','Northern Mariana Islands','Северные Марианские Острова','Північні Маріанські Острови','1670','MP');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MQ','Martinique','Мартиника','Мартініка ','596','MQ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MR','Mauritania','Мавритания','Мавританія ','222','MR');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MS','Montserrat','Монсеррат','Монтсеррат ','1664','MS');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MT','Malta','Мальта','Мальта','356','MT');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MU','Mauritius Island','Маврикий','Маврикій','230','MU');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MV','Maldives Islands','Мальдивы','Мальдіви ','960','MV');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MW','Malawi','Малави','Малаві','265','MW');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MX','Mexico','Мексика','Мексика','52','MX');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MY','Malaysia','Малайзия','Малайзія','60','MY');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('MZ','Mozambique','Мозамбик','Мозамбік','258','MZ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('NA','Namibia','Намибия','Намібія','264','NA');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('NC','New Caledonia','Новая Каледония','Нова Каледонія','687','NC');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('NE','Niger','Нигер','Нігер ','227','NE');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('NF','Norfolk Island','Норфолк Айленд','Норфолк Айленд ',NULL,'NF');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('NG','Nigeria','Нигерия','Нігерія','234','NG');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('NI','Nicaragua','Никарагуа','Нікарагуа','505','NI');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('NL','Netherlands','Нидерланды','Нідерланди','31','NL');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('NO','Norway','Норвегия','Норвегія','47','NO');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('NP','Nepal','Непал','Непал','977','NP');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('NR','Nauru','Науру','Науру','674','NR');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('NU','Niue','Ниуэ','Ніуе ','683','NU');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('NZ','New Zealand','Новая Зеландия','Нова Зеландія','64','NZ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('OM','Oman','Оман','Оман','968','OM');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('PA','Panama','Панама','Панама','507','PA');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('PE','Peru','Перу','Перу','51','PE');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('PF','French Polynesia','Французская Полинезия','Французька Полінезія ','689','PF');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('PG','Papua New Guinea','Папуа - Новая Гвинея','Папуа Нова Гвінея','675','PG');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('PH','Philippines','Филиппины','Філіпіни','63','PH');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('PK','Pakistan','Пакистан','Пакистан','92','PK');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('PL','Poland','Польша','Польща','48','PL');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('PM','St. Pierre and Miquelon','Сен-Пьер и Микелон','Сен Пєр та Мікелон','508','PM');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('PR','Puerto Rico','Пуэрто Рико','Пуерто-Ріко ','1787','PR');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('PS','Palestinian Occ. Territories','Палестина','Палестина','972','PS');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('PT','Portugal','Португалия','Португалія','351','PT');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('PW','Palau Islands','Палау','Палау','680','PW');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('PY','Paraguay','Парагвай','Парагвай','595','PY');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('QA','Qatar','Катар','Катар','974','QA');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('RE','Reunion Island','Реюньон','Реюньйон ','262','RE');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('RO','Romania','Румыния','Румунія','40','RO');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('RS','Serbia','Сербия','Сербія','381','RS');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('RU','Russia','Россия','Росія','7','RU');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('RW','Rwanda','Руанда','Руанда','250','RW');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SA','Saudi Arabia','Саудовская Аравия','Саудівська Аравія','966','SA');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SB','Solomon Islands','Соломоновы острова','Соломонові Острови ','677','SB');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SC','Seychelles Islands','Сейшельские острова','Сейшели','248','SC');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SD','Sudan','Судан','Судан','249','SD');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SE','Sweden','Швеция','Швеція','46','SE');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SG','Singapore','Сингапур','Сінгапур','65','SG');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SH','St. Helena Island','Остров святой Елены','Острів Святої Єлени ','290','SH');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SI','Slovenia','Словения','Словенія','386','SI');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SK','Slovakia','Словакия','Словаччина','421','SK');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SL','Sierra Leone','Сьерра-Леоне','Сьєрра-Леоне ','232','SL');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SM','San Marino','Сан-Марино','Сан-Марино ','378','SM');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SN','Senegal','Сенегал','Сенегал','221','SN');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SO','Somalia','Сомали','Сомалі','252','SO');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SR','Suriname','Суринам','Сурінам ','597','SR');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('ST','Sao Tome and Principe Islands','Сан-Томе и Принсипи','Сан-Томе і Принсіпі','239','ST');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SV','El Salvador','Сальвадор','Сальвадор','503','SV');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SY','Syrian Arab Republic','Сирия','Сирія','963','SY');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('SZ','Swaziland','Свазиленд','Свазіленд','268','SZ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('TC','Turks and Caicos Islands','Теркс и Кайкос','Теркс і Кайкос',NULL,'TC');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('TD','Chad','Чад','Чад','235','TD');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('TG','Togo','Того','Того','228','TG');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('TH','Thailand','Таиланд','Таїланд','66','TH');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('TJ','Tajikistan','Таджикистан','Таджикистан','992','TJ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('TL','Timor Leste','Тимор-Лешти','Тимор-Лешті','670','TL');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('TM','Turkmenistan','Туркменистан','Туркменістан','993','TM');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('TN','Tunisia','Тунис','Туніс','216','TN');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('TO','Tonga','Тонга','Тонга','676','TO');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('TR','Turkey','Турция','Туреччина','90','TR');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('TT','Trinidad and Tobago','Тринидад и Тобаго','Тринідад і Тобаго','1868','TT');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('TV','Tuvalu','Тувалу','Тувалу','688','TV');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('TW','Taiwan','Тайвань','Тайвань','886','TW');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('TZ','Tanzania (United Republic)','Танзания','Танзанія','255','TZ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('UA','Ukraine','Украина','Україна','38','UA');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('UG','Uganda','Уганда','Уганда','256','UG');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('UM','U.S. Minor Outlying Islands','Внешние малые острова (CШA)','Зовнішні малі острови (CШA)','1','UM');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('US','USA','США','Сполучені Штати Америки','1','US');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('UY','Uruguay','Уругвай','Уругвай','598','UY');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('UZ','Uzbekistan','Узбекистан','Узбекистан','998','UZ');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('VC','St Vincent and the Grenadines','Сент-Винсент и Гренадины','Сент-Вінсент і Ґренадини','1784','VC');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('VE','Venezuela','Венесуэла','Венесуела','58','VE');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('VG','Virgin Islands (British)','Британские Виргинские острова','Британські Віргінські острови','1284','VG');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('VI','Virgin Islands US','Американские Виргинские острова','Американські Віргінські острови','1284','VI');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('VN','Viet Nam','Вьетнам','Вєтнам','84','VN');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('VU','Vanuatu','Вануату','Вануату','678','VU');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('WF','Wallis and Futuna Islands','Острова Уоллис и Футун','Острови Волліс і Футуна ','681','WF');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('WS','Samoa (Independent State of)','Самоа','Самоа','685','WS');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('YE','Yemen (Arab Republic)','Йемен','Ємен','967','YE');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('YT','Mayotte','Майотта','Майотта','269','YT');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('ZA','South Africa','ЮАР','Південно-африканська республіка','27','ZA');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('ZM','Zambia','Замбия','Замбія','260','ZM');
insert into `countries` (`code`, `name_en`, `name_ru`, `name_uk`, `country_phone`, `code`) values('ZW','Zimbabwe','Зимбабве','Зімбабве','263','ZW');
